##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Ansible Part 3: Your Network as Code
# Author: Hank Preston <hapresto@cisco.com>
#
# Illustrate the following concepts:
# -
##############################################################
---
- name: "Generate NETCONF OSPF config"
  tags: [api, netconf, ospf]
  template:
    src: "files/ned_ospf.j2"
    dest: "./configs/{{inventory_hostname}}-ospf.xml"

- name: Configure OSPF with NETCONF
  tags: [api, netconf, ospf]
  netconf_config:
    host: "{{inventory_hostname}}"
    hostkey_verify: false
    src: "./configs/{{inventory_hostname}}-ospf.xml"
