##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Ansible Part 3: Your Network as Code
# Author: Hank Preston <hapresto@cisco.com>
#
# Illustrate the following concepts:
# -
##############################################################
---
# - name: "Retrieving NX-OS Facts"
#   nxos_facts:
#     provider:
#       host: "{{inventory_hostname}}"
#   register: facts
#
# - name: "Print Facts"
#   debug: msg="{{facts}}"

- name: Enable NX-API
  tags: [api, nxapi]
  nxos_feature:
    provider:
      host: "{{inventory_hostname}}"
    feature: nxapi
    state: enabled
